export const REMOVE_CHALLENGE_FACTOR = 'REMOVE_CHALLENGE_FACTOR';
export const SET_CHALLENGE = 'SET_CHALLENGE';
export const RESET_CHALLENGE_FACTOR = 'RESET_CHALLENGE_FACTOR';
export const ADD_QUESTION_TO_CHALLENGE = 'ADD_QUESTION_TO_CHALLENGE';
export const SET_CHALLENGE_TROPHY = 'SET_CHALLENGE_TROPHY';
export const SET_ALL_CHALLENGES = 'SET_ALL_CHALLENGES';
export const ADD_TO_CHALLENGE_HISTORY = 'ADD_TO_CHALLENGE_HISTORY';
